import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#d4e3ff",
        "on-primary-fixed-variant": "#004e5c",
        "surface-tint": "#4cd7f6",
        "on-tertiary": "#00315d",
        "tertiary": "#a4c9ff",
        "secondary": "#adc6ff",
        "secondary-fixed": "#d8e2ff",
        "on-surface": "#e4e1e9",
        "surface-variant": "#35343a",
        "surface-container-lowest": "#0e0e13",
        "on-primary-fixed": "#001f26",
        "surface-container-highest": "#35343a",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#e6ecff",
        "surface-container-low": "#1b1b20",
        "inverse-on-surface": "#303036",
        "surface-container": "#1f1f25",
        "on-tertiary-fixed": "#001c39",
        "on-error": "#690005",
        "error-container": "#93000a",
        "surface-container-high": "#2a292f",
        "on-secondary": "#002e6a",
        "on-primary": "#003640",
        "on-secondary-fixed-variant": "#004395",
        "inverse-surface": "#e4e1e9",
        "primary": "#4cd7f6",
        "on-tertiary-container": "#003d70",
        "secondary-container": "#0566d9",
        "on-tertiary-fixed-variant": "#004883",
        "surface-bright": "#39383e",
        "tertiary-container": "#64a9fe",
        "primary-container": "#06b6d4",
        "on-background": "#e4e1e9",
        "on-primary-container": "#00424f",
        "primary-fixed-dim": "#4cd7f6",
        "inverse-primary": "#00687a",
        "background": "#131318",
        "surface": "#131318",
        "on-surface-variant": "#bcc9cd",
        "on-secondary-fixed": "#001a42",
        "tertiary-fixed-dim": "#a4c9ff",
        "error": "#ffb4ab",
        "outline-variant": "#3d494c",
        "primary-fixed": "#acedff",
        "secondary-fixed-dim": "#adc6ff",
        "surface-dim": "#131318",
        "outline": "#869397",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "margin-lg": "6rem",
        "gutter-lg": "2rem",
        "gutter-sm": "1rem",
        "margin": "1.5rem",
        "gutter": "1.5rem",
        "margin-md": "3rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-button": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-eyebrow": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-tech": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-hero": ["64px", { lineHeight: "72px", letterSpacing: "-0.03em", fontWeight: "300" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-hero-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-button": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.025em", fontWeight: "400" }],
        "label-eyebrow": ["11px", { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-tech": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
